### ISSUE TITLE
After adding 3.2.3 again, there are three compilation errors

### ISSUE THREAD

**Issue by Kojima648** [DominicdeGraaf/Unity-Post-Processing-Stack#1]
![图片](https://github.com/DominicdeGraaf/Unity-Post-Processing-Stack/assets/20067002/84550f56-6e44-48da-a119-4448b4f2ebc1)
![图片](https://github.com/DominicdeGraaf/Unity-Post-Processing-Stack/assets/20067002/e4ebea40-94d5-4197-9247-add203af402d)

**Comment by DominicdeGraaf** [comment]
Do you also have the FSR 3 or DLSS packages in your project? Could you upload a screenshot of the scriptable defines in the player settings?

**Comment by Kojima648** [comment]
![图片](https://github.com/DominicdeGraaf/Unity-Post-Processing-Stack/assets/20067002/c3a91946-ce4a-4535-bdd1-b5fbe2b77df0)
![图片](https://github.com/DominicdeGraaf/Unity-Post-Processing-Stack/assets/20067002/a30e9a90-f3d1-4d15-83c7-1c97af679683)

We are using NVIDIA graphics cards, I don't know what else is missing?

**Comment by DominicdeGraaf** [comment]
Please change the AEG_FSR2 define to AEG_FSR3.

Additionally after doing this I recommend you to update my FSR asset to the latest version.

**Comment by Kojima648** [comment]
OK， I will try tomorrow, and if there are no issues, I will close this order
